name: CreatePR

on:
  workflow_dispatch:

    inputs:
      owner:
        description: 'Account Owner (erwin-inc)'
        required: true
        default: 'erwin-inc'
      repository:
        description: 'This repository'
        required: true
        default: 'zeta-shared-actions'
      base:
        description: 'Base branch (to merge into)'
        required: true
        default: 'master'
      head:
        description: 'Head branch (to merge from - release/xx.xx.xx)'
        required: true
        default: ''

jobs:
  adding-parameters:
    runs-on: ubuntu-latest
    name: Run JS to create PR
    steps:
      - name: Step - Create the PR
        id: CreatePR
        uses: erwin-inc/zeta-shared-actions@master
        with:
          owner: ${{ github.event.inputs.owner }}
          repository: ${{ github.event.inputs.repository }}
          base: ${{ github.event.inputs.base }}
          head: ${{ github.event.inputs.head }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `CreatePR` step
      - name: Step - Get the output
        run: echo "The output was ${{ steps.CreatePR.outputs.output }}"

